apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "mongodb-replicaset.name" . }}
    chart: {{ template "mongodb-replicaset.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "mongodb-replicaset.fullname" . }}
data:
  mongod.conf: |
    replication: 
      replSetName: {{ .Release.Name }}
    {{- if eq .Release.Name "cfg" }}
    sharding:
      clusterRole: configsvr
    {{- else }}
    sharding:
      clusterRole: shardsvr
    {{- end }}
{{ toYaml .Values.configmap | indent 4 }}
